const express=require('express'),path=require('path'),crypto=require('crypto'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),helmet=require('helmet'),cors=require('cors');
const {Pool}=require('pg');const app=express(),PORT=process.env.PORT||10000,DB=process.env.DATABASE_URL,SECRET=process.env.JWT_SECRET||'mf-change-me';
const pool=new Pool({connectionString:DB,ssl:DB&&!DB.includes('localhost')?{rejectUnauthorized:false}:false});const q=(s,p=[])=>pool.query(s,p),uid=()=>crypto.randomUUID(),plate=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,7),money=n=>+Number(n||0).toFixed(2);
app.use(helmet({contentSecurityPolicy:false}));app.use(cors());app.use(express.json({limit:'5mb'}));
async function init(){await q(`
CREATE TABLE IF NOT EXISTS users(id text primary key,name text not null,email text unique not null,password_hash text not null,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS clients(id text primary key,name text not null,phone text,email text,cpf_cnpj text,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS inventory(id text primary key,sku text,name text not null,category text,quantity int default 0,min_quantity int default 3,cost numeric(12,2) default 0,price numeric(12,2) default 0,moto_models text[] default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
CREATE TABLE IF NOT EXISTS vehicle_cache(plate text primary key,brand text,model text,year text,color text,source text,updated_at timestamptz default now());
CREATE TABLE IF NOT EXISTS service_orders(id text primary key,client_id text references clients(id) on delete set null,client_name text,plate text not null,brand text,model text,year text,color text,description text not null,status text default 'pendente',estimated_cost numeric(12,2) default 0,final_cost numeric(12,2) default 0,created_at timestamptz default now(),updated_at timestamptz default now());
CREATE TABLE IF NOT EXISTS budgets(id text primary key,client_name text,plate text,items jsonb default '[]',grand_total numeric(12,2) default 0,status text default 'aberto',created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS sales(id text primary key,client_name text,items jsonb default '[]',subtotal numeric(12,2) default 0,discount numeric(12,2) default 0,total numeric(12,2) default 0,payment_method text,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS fiscal_documents(id text primary key,sale_id text references sales(id) on delete set null,type text default 'NFC-e',client_name text,client_document text,items jsonb default '[]',total numeric(12,2) default 0,status text default 'rascunho',provider_ref text,access_key text,error_message text,created_at timestamptz default now(),updated_at timestamptz default now());`)}
const wrap=f=>(r,s,n)=>Promise.resolve(f(r,s,n)).catch(n);function auth(r,s,n){try{r.user=jwt.verify((r.headers.authorization||'').replace('Bearer ',''),SECRET);n()}catch{s.status(401).json({error:'Faça login novamente.'})}}
app.get('/api/health',wrap(async(_,s)=>{await q('select 1');s.json({ok:true,app:'MF Moto Peças'})}));
app.post('/api/auth/register',wrap(async(r,s)=>{let{name,email,password}=r.body;email=String(email||'').toLowerCase().trim();if(!name||!email||String(password).length<6)return s.status(400).json({error:'Preencha nome, e-mail e senha (6+ caracteres).'});if((await q('select 1 from users where email=$1',[email])).rowCount)return s.status(409).json({error:'E-mail já cadastrado.'});let u={id:uid(),name:String(name).trim(),email};await q('insert into users values($1,$2,$3,$4,now())',[u.id,u.name,u.email,await bcrypt.hash(password,12)]);s.json({token:jwt.sign({sub:u.id,name:u.name,email:u.email},SECRET,{expiresIn:'7d'}),user:u})}));
app.post('/api/auth/login',wrap(async(r,s)=>{let u=(await q('select * from users where email=$1',[String(r.body.email||'').toLowerCase().trim()])).rows[0];if(!u||!await bcrypt.compare(String(r.body.password||''),u.password_hash))return s.status(401).json({error:'E-mail ou senha incorretos.'});s.json({token:jwt.sign({sub:u.id,name:u.name,email:u.email},SECRET,{expiresIn:'7d'}),user:{id:u.id,name:u.name,email:u.email}})}));
app.get('/api/me',auth,(r,s)=>s.json(r.user));
app.get('/api/dashboard',auth,wrap(async(_,s)=>{let [c,o,i,b,v,l]=await Promise.all([q('select count(*)::int n from clients'),q("select count(*)::int n,count(*) filter(where status<>'concluido')::int open from service_orders"),q('select count(*)::int n from inventory'),q('select count(*)::int n from budgets'),q("select coalesce(sum(total),0)::float total,count(*)::int n from sales where created_at>=date_trunc('day',now())"),q('select count(*)::int n from inventory where quantity<=min_quantity')]);s.json({clients:c.rows[0].n,orders:o.rows[0].n,open_orders:o.rows[0].open,inventory:i.rows[0].n,budgets:b.rows[0].n,today_sales:v.rows[0].total,today_sales_count:v.rows[0].n,low_stock:l.rows[0].n})}));
// clientes
app.get('/api/clients',auth,wrap(async(_,s)=>s.json((await q('select * from clients order by created_at desc')).rows)));
app.post('/api/clients',auth,wrap(async(r,s)=>{let x=r.body;if(!x.name)return s.status(400).json({error:'Nome obrigatório.'});s.json((await q('insert into clients(id,name,phone,email,cpf_cnpj) values($1,$2,$3,$4,$5) returning *',[uid(),x.name,x.phone||'',x.email||'',x.cpf_cnpj||''])).rows[0])}));
app.delete('/api/clients/:id',auth,wrap(async(r,s)=>{await q('delete from clients where id=$1',[r.params.id]);s.json({ok:true})}));
// estoque
app.get('/api/inventory',auth,wrap(async(_,s)=>s.json((await q('select *,quantity<=min_quantity as is_low_stock from inventory order by name')).rows.map(x=>({...x,cost:+x.cost,price:+x.price})))));
app.post('/api/inventory',auth,wrap(async(r,s)=>{let x=r.body,m=Array.isArray(x.moto_models)?x.moto_models:String(x.moto_models||'').split(',').map(v=>v.trim()).filter(Boolean);s.json((await q('insert into inventory(id,sku,name,category,quantity,min_quantity,cost,price,moto_models) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[uid(),x.sku||'',x.name,x.category||'',+x.quantity||0,+x.min_quantity||3,money(x.cost),money(x.price),m])).rows[0])}));
app.delete('/api/inventory/:id',auth,wrap(async(r,s)=>{await q('delete from inventory where id=$1',[r.params.id]);s.json({ok:true})}));
// placa: cache -> histórico -> placai -> APIBrasil
async function cache(p,d,source){await q(`insert into vehicle_cache(plate,brand,model,year,color,source) values($1,$2,$3,$4,$5,$6) on conflict(plate) do update set brand=excluded.brand,model=excluded.model,year=excluded.year,color=excluded.color,source=excluded.source,updated_at=now()`,[p,d.brand||'',d.model||'',d.year||'',d.color||'',source])}
async function placai(p){try{let a=await fetch('https://www.placai.com/api/placaOrder',{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0'},body:JSON.stringify({placa:p,product_id:1,utm:{},score:'0.0'}),signal:AbortSignal.timeout(8000)});if(!a.ok)return null;let tid=(await a.json())?.data?.transaction_id;if(!tid)return null;await new Promise(r=>setTimeout(r,1500));let b=await fetch(`https://www.placai.com/api/resultado/${tid}/preview`,{headers:{'user-agent':'Mozilla/5.0'},signal:AbortSignal.timeout(8000)});let v=(await b.json())?.data?.veiculo||{};return v.fabricante||v.modelo?{brand:v.fabricante,model:v.modelo,year:v.ano_fabricacao,color:v.cor}:null}catch{return null}}
async function apibrasil(p){if(!process.env.APIBRASIL_BEARER_TOKEN||!process.env.APIBRASIL_DEVICE_TOKEN)return null;try{let r=await fetch('https://gateway.apibrasil.io/api/v2/vehicles/dados',{method:'POST',headers:{'content-type':'application/json',DeviceToken:process.env.APIBRASIL_DEVICE_TOKEN,Authorization:`Bearer ${process.env.APIBRASIL_BEARER_TOKEN}`},body:JSON.stringify({placa:p}),signal:AbortSignal.timeout(9000)});let v=(await r.json()).response||{};return v.MARCA||v.MODELO?{brand:v.MARCA,model:v.MODELO,year:String(v.ANO||v.ano||''),color:v.COR||v.cor}:null}catch{return null}}
app.get('/api/vehicle/:p',auth,wrap(async(r,s)=>{let p=plate(r.params.p);if(p.length<7)return s.status(400).json({error:'Placa inválida.'});let a=(await q('select brand,model,year,color,source from vehicle_cache where plate=$1',[p])).rows[0];if(a)return s.json({found:true,plate:p,...a});a=(await q('select brand,model,year,color from service_orders where plate=$1 order by created_at desc limit 1',[p])).rows[0];if(a&&(a.brand||a.model)){await cache(p,a,'historico');return s.json({found:true,plate:p,source:'historico',...a})}a=await placai(p);let src='placai';if(!a){a=await apibrasil(p);src='apibrasil'}if(a){await cache(p,a,src);return s.json({found:true,plate:p,source:src,...a})}s.json({found:false,plate:p,message:'Não localizado automaticamente. Preencha manualmente; ficará salvo no histórico.'})}));
// ordens
app.get('/api/orders',auth,wrap(async(_,s)=>s.json((await q('select * from service_orders order by created_at desc')).rows.map(x=>({...x,estimated_cost:+x.estimated_cost,final_cost:+x.final_cost})))));
app.post('/api/orders',auth,wrap(async(r,s)=>{let x=r.body,p=plate(x.plate);if(p.length<7)return s.status(400).json({error:'Placa inválida.'});let row=(await q(`insert into service_orders(id,client_id,client_name,plate,brand,model,year,color,description,status,estimated_cost) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[uid(),x.client_id||null,x.client_name||'',p,x.brand||'',x.model||'',x.year||'',x.color||'',x.description||'',x.status||'pendente',money(x.estimated_cost)])).rows[0];await cache(p,x,'ordem');s.json(row)}));
app.put('/api/orders/:id',auth,wrap(async(r,s)=>{let x=r.body;s.json((await q(`update service_orders set status=$1,description=$2,estimated_cost=$3,final_cost=$4,updated_at=now() where id=$5 returning *`,[x.status,x.description,money(x.estimated_cost),money(x.final_cost),r.params.id])).rows[0])}));
app.delete('/api/orders/:id',auth,wrap(async(r,s)=>{await q('delete from service_orders where id=$1',[r.params.id]);s.json({ok:true})}));
// orçamentos + IA
app.get('/api/budgets',auth,wrap(async(_,s)=>s.json((await q('select * from budgets order by created_at desc')).rows.map(x=>({...x,grand_total:+x.grand_total})))));
app.post('/api/budgets',auth,wrap(async(r,s)=>{let x=r.body,it=x.items||[],t=money(x.grand_total??it.reduce((a,b)=>a+(+b.total||0),0));s.json((await q('insert into budgets(id,client_name,plate,items,grand_total,status) values($1,$2,$3,$4,$5,$6) returning *',[uid(),x.client_name||'',plate(x.plate),JSON.stringify(it),t,x.status||'aberto'])).rows[0])}));
function normText(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9$., ]/g,' ').replace(/\s+/g,' ').trim()}
const numWords={um:1,uma:1,dois:2,duas:2,tres:3,quatro:4,cinco:5,seis:6,sete:7,oito:8,nove:9,dez:10};
function qtyFromMessage(m){let n=normText(m),a=n.match(/^\s*(\d{1,3})\b/);if(a)return Math.max(1,+a[1]);for(let [w,v] of Object.entries(numWords))if(new RegExp('^'+w+'\\b').test(n))return v;return 1}
function explicitPrice(m){let n=normText(m),tests=[/r\$\s*(\d+(?:[.,]\d{1,2})?)/,/\b(?:de|por|a)\s+(\d+(?:[.,]\d{1,2})?)\s*(?:reais|real|cada)?\b/,/\b(\d+(?:[.,]\d{1,2})?)\s*(?:reais|real)\b/];for(let re of tests){let x=n.match(re);if(x)return money(String(x[1]).replace(',','.'))}return 0}
function localBudget(message,rows){let raw=String(message||'').trim(),n=normText(raw),qty=qtyFromMessage(raw),given=explicitPrice(raw),stop=new Set(['quero','preciso','orcamento','de','do','da','para','por','com','sem','um','uma','dois','duas','tres','quatro','cinco','seis','sete','oito','nove','dez','reais','real','cada','r']);let words=n.split(' ').filter(x=>x.length>2&&!stop.has(x)&&!/^\d/.test(x));let best=null,score=0;for(let p of rows){let hay=normText([p.name,p.category,(p.moto_models||[]).join(' ')].join(' '));let s=words.reduce((a,w)=>a+(hay.includes(w)?1:0),0);if(s>score){score=s;best=p}}let unit=0,fromInventory=false,name='Item informado';if(best&&score>0){name=best.name;unit=money(best.price);fromInventory=unit>0}if(!unit&&given){unit=given;name=(best&&best.name)||raw.replace(/\b(?:de|por|a)\s+r?\$?\s*\d+(?:[.,]\d{1,2})?\s*(?:reais|real|cada)?\b/i,'').trim()||'Item informado'}let item={name:name,quantity:qty,unit_price:unit,total:money(qty*unit),from_inventory:fromInventory,needs_price:!unit};if(!unit)return {reply:'Não encontrei um preço para esse item. Cadastre a peça no estoque ou informe o valor unitário no pedido.',items:[item],grand_total:0,provider:'local-gratis'};let unitText=unit.toFixed(2).replace('.',','),totalText=item.total.toFixed(2).replace('.',',');return {reply:'Orçamento calculado: '+qty+'x '+name+' a R$ '+unitText+' = R$ '+totalText+'.',items:[item],grand_total:item.total,provider:'local-gratis'}}
function parseAIText(txt){try{let t=String(txt||'').trim(),f=String.fromCharCode(96).repeat(3);if(t.startsWith(f)){let p=t.indexOf('\n');if(p>=0)t=t.slice(p+1);if(t.endsWith(f))t=t.slice(0,-3)}return JSON.parse(t.trim())}catch{return null}}
async function openAIBudget(key,model,prompt){let rr=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+key},body:JSON.stringify({model:model,input:prompt,max_output_tokens:1200}),signal:AbortSignal.timeout(20000)}),d=await rr.json();if(!rr.ok)throw new Error((d&&d.error&&d.error.message)||'Falha no provedor de IA.');let txt=d.output_text||(d.output||[]).flatMap(o=>o.content||[]).map(x=>x.text||'').join('');let parsed=parseAIText(txt);if(!parsed)throw new Error('Resposta de IA inválida.');return parsed}
app.post('/api/ai/budget',auth,wrap(async(r,s)=>{let rows=(await q('select name,category,price,quantity,moto_models from inventory order by name')).rows;let provider=String(process.env.AI_PROVIDER||'local').toLowerCase();if(provider==='openai'&&process.env.OPENAI_API_KEY){let inv=rows.map(x=>x.name+'|'+x.price+'|'+x.quantity+'|'+(x.moto_models||[]).join(',')).join('\n');let prompt='Você é o orçamentista da MF Moto Peças. Use somente preços do estoque abaixo ou preços informados pelo usuário. Nunca invente valor. Retorne SOMENTE JSON no formato {"reply":"texto","items":[{"name":"","quantity":1,"unit_price":0,"total":0,"from_inventory":true,"needs_price":false}],"grand_total":0}.\nESTOQUE:\n'+inv+'\nPEDIDO:'+String(r.body.message||'');try{let out=await openAIBudget(process.env.OPENAI_API_KEY,process.env.OPENAI_MODEL||'gpt-4.1-mini',prompt);return s.json(Object.assign({},out,{provider:'openai'}))}catch(e){console.warn('IA externa indisponível, usando modo local:',e.message)}}return s.json(localBudget(r.body.message,rows))}));

// PDV
app.get('/api/sales',auth,wrap(async(_,s)=>s.json((await q('select * from sales order by created_at desc')).rows.map(x=>({...x,total:+x.total})))));
app.post('/api/sales',auth,wrap(async(r,s)=>{let items=r.body.items||[];if(!items.length)return s.status(400).json({error:'Carrinho vazio.'});let c=await pool.connect();try{await c.query('begin');let out=[],sub=0;for(let z of items){let p=(await c.query('select * from inventory where id=$1 for update',[z.inventory_id])).rows[0],qty=Math.max(1,+z.quantity||1);if(!p||p.quantity<qty)throw new Error('Estoque insuficiente: '+(p?.name||'item'));await c.query('update inventory set quantity=quantity-$1 where id=$2',[qty,p.id]);let u=money(z.unit_price??p.price),t=money(qty*u);sub+=t;out.push({inventory_id:p.id,name:p.name,quantity:qty,unit_price:u,total:t})}let disc=money(r.body.discount),total=money(Math.max(0,sub-disc)),row=(await c.query('insert into sales(id,client_name,items,subtotal,discount,total,payment_method) values($1,$2,$3,$4,$5,$6,$7) returning *',[uid(),r.body.client_name||'',JSON.stringify(out),money(sub),disc,total,r.body.payment_method||'pix'])).rows[0];await c.query('commit');s.json(row)}catch(e){await c.query('rollback');s.status(400).json({error:e.message})}finally{c.release()}}));
// fiscal: nunca finge emissão sem provedor autorizado
app.get('/api/fiscal',auth,wrap(async(_,s)=>s.json((await q('select * from fiscal_documents order by created_at desc')).rows.map(x=>({...x,total:+x.total})))));
app.post('/api/fiscal',auth,wrap(async(r,s)=>{let x=r.body;s.json((await q('insert into fiscal_documents(id,sale_id,type,client_name,client_document,items,total) values($1,$2,$3,$4,$5,$6,$7) returning *',[uid(),x.sale_id||null,x.type||'NFC-e',x.client_name||'',x.client_document||'',JSON.stringify(x.items||[]),money(x.total)])).rows[0])}));
app.post('/api/fiscal/:id/issue',auth,wrap(async(r,s)=>{if(!process.env.FISCAL_PROVIDER_URL||!process.env.FISCAL_PROVIDER_TOKEN)return s.status(409).json({error:'Emissão oficial exige FISCAL_PROVIDER_URL e FISCAL_PROVIDER_TOKEN de provedor homologado/SEFAZ.'});let d=(await q('select * from fiscal_documents where id=$1',[r.params.id])).rows[0],rr=await fetch(process.env.FISCAL_PROVIDER_URL,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.FISCAL_PROVIDER_TOKEN}`},body:JSON.stringify(d)}),x=await rr.json();if(!rr.ok)return s.status(502).json({error:x.message||'Rejeitada pelo provedor.'});s.json((await q("update fiscal_documents set status='emitida',provider_ref=$1,access_key=$2,updated_at=now() where id=$3 returning *",[x.id||x.ref||'',x.access_key||x.chave||'',d.id])).rows[0])}));
app.use(express.static(path.join(__dirname,'public')));app.get(/^(?!\/api).*/,(_,s)=>s.sendFile(path.join(__dirname,'public/index.html')));app.use((e,r,s,n)=>{console.error(e);s.status(500).json({error:e.message||'Erro interno.'})});init().then(()=>app.listen(PORT,()=>console.log('MF Moto Peças online',PORT))).catch(e=>{console.error(e);process.exit(1)});
